# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Medtrail_Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Kingfisher'


  # Pods for Medtrail_Assignment

end
